### ISSUE TITLE
Information Architecture & User flows + Basic Design system

### ISSUE THREAD

**Issue by sahil8701** [KeysFortress/cloud#3]

**Comment by KristiforMilchev** [comment]
I am going to close this one and split it into 2 more, as the user flow belongs to the frontend repositories. This one is only for the cloud code. 

This one should be ok for the cloud part, I am almost done with the user flow chart as well, so i will upload that one as soon as i am done with it, i guess this one doesn't really help much with your stuff, so yeah, I will tag you once i am ready. 

@sahil8701

**Comment by sahil8701** [comment]
Sure, that works for me.
